name: Deploy LMS on Firebase

on:
  push:
    branches:
      - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16.14.0"
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: "1//09GqUmn8K4ZW_CgYIARAAGAkSNwF-L9IrSjtR-S4s1LdNw74nw0UNSfwLiGrBImlpBaTTQldVOi4nyB2ANDE_oDJmKvh7Q6U1uwo"
